### ISSUE TITLE
application requires OS X 10.13 or later

### ISSUE THREAD

**Issue by ziqbal** [sausheong/invadersapp#1]
Hi,

After successfully compiling on a mac 10.10.5 , running the app I'm getting a pop saying:

"You can’t use this version of the application “Invaders” with this version of OS X. You have OS X 10.10.5. The application requires OS X 10.13 or later."

The invaders icon also has some kind of sign indicating it is not runnable.

Any ideas what is going on and how I could get the code to run?

Thank you for publishing your project.

**Comment by sausheong** [comment]
Have you tried to run it from the terminal? You can do a normal `go build` and that will generate an `invaderapp` binary.

**Comment by ziqbal** [comment]
Yes! Running from command line ( "./invadersapp" ) worked.

Thank you for the suggestion.

For convenience I created an executable "run.command" file with the following contents:

```
#!/bin/bash
cd -- "$(dirname "$0")"
./invadersapp
```

Now I can double click this and everything works as expected.
