### ISSUE TITLE
Couple of improvements...

### ISSUE THREAD

**Issue by pulkitsharma07** [sausheong/invadersapp#2]
Interesting ! Couple of improvements that I feel will make it even better :-)
Would love to know what your take on these...

1. Render on the front-end ? [ Though it is a neat idea to generate frames on the server and send it to the front-end, but it will inherently put a limit of the framerate, even though everything is running locally ]

2. Establish a websocket connection from the webview for requesting frames(or serialised game objects if you go with 1.) and sending key presses? [ No overhead of separate HTTP calls, decoupling frontend and backend will allow you to add multiplayer, like LAN play without internet :-D ]

3. Play sounds in a goroutine ?

4. Do not hard code the port ?

**Comment by sausheong** [comment]
Thanks for the comments!

1. The framerate _should_ be better if it's rendered at the front-end but I'm not sure how much better or if it makes a difference. I feel that the effort to build the frame will likely take up more effort and time than showing it on the screen through a browser but I'm not sure. Also, I'm a much better (relatively) server-side web developer than a front-end one (I'm terrible with Javascript) :)

2. Not sure if doing websockets add any value? I kept it as normal HTTP calls to make the game really simple to understand

3. It's possible, again not sure of it's additional value. Probably will do that if I'm playing some background music.

4. Hardcoding the port was a quick and dirty way and also pretty easy to debug. Someone just sent a PR for creating ephemeral ports :)

**Comment by pulkitsharma07** [comment]
Agreed 👍
